### ISSUE TITLE
Create a Jupyter Notebook

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#5]
-Create a jupyter notebook called trigrams.ipynb, where all tasks should be completed in.

note: 
For each task, you should write your code in code cells while using MarkDown cells to give explanations and insights into your code. Break up your code into smaller, manageable cells whenever possible. Each code cell should focus on a single step in your overall solution.

Include comments in all code cells to tell the reader what each statement does. Write clean, readable, and efficient code, using meaningful variable names and consistent formatting. You should follow Python coding standards and guidelines such as [PEP8](https://peps.python.org/pep-0008/).

**Comment by moudgalya1223** [comment]
Hey can you give me some more inputs , on this like you wanted to create a ipnyp or an online compiler ? @JakubSzkup1  and can you assign this to me
